package main.game.weapons.stats;

public enum WeaponStatType {
    BULLET_DAMAGE,
    BULLET_DAMAGE_FALLOFF_PCT,
    BULLET_DAMAGE_FALLOFF_DISTANCE_MIN,
    BULLET_DAMAGE_FALLOFF_DISTANCE_MAX,
    BULLET_SPEED,
    BULLET_NUM,
    BULLET_ACCELERATION,
    BULLET_SIZE,
    BULLET_BOUNCE,
    BULLET_LIFETIME,
    BULLET_KNOCKBACK,

    WEAPON_ACCURACY,
    WEAPON_SPREAD,
    WEAPON_FIRE_RATE,
    WEAPON_KICK,
    WEAPON_LIFESTEAL,
    WEAPON_CLIP_SIZE,

    PLAYER_SPEED,
    PLAYER_HEALTH,
    PLAYER_REGEN,
    PLAYER_RESISTANCE,

    EXPLOSION_DAMAGE,
    EXPLOSION_RADIUS,
    EXPLOSION_KNOCKBACK,

    FIRE_DAMAGE,
    FIRE_DURATION,
    FIRE_SPREAD_CHANCE,

    LIGHTNING_DAMAGE,
    LIGHTNING_MAX_BOUNCES,
    LIGHTNING_STUN_PCT,
    LIGHTNING_STUN_DURATION,
}
